library("RSQLite")
chinookdb <- dbConnect(RSQLite::SQLite(), "datasets/chinook.db")
dbListTables(chinookdb)
dbGetQuery(chinookdb, "SELECT * FROM media_types;")
dbGetQuery(chinookdb, "SELECT * FROM media_types WHERE MediaTypeID <= 3;")
dbGetQuery(chinookdb, "SELECT * FROM media_types WHERE MediaTypeID BETWEEN 2 AND 4;")
dbListFields(chinookdb, "invoices")
dbListFields(chinookdb, "invoice_items")
dbGetQuery(chinookdb, "SELECT InvoiceID, CustomerID FROM invoices UNION SELECT InvoiceID, Quantity FROM invoice_items;")
dbGetQuery(chinookdb, "SELECT InvoiceID, CustomerID FROM invoices INTERSECT SELECT InvoiceID, Quantity FROM invoice_items;")
dbGetQuery(chinookdb, "SELECT * FROM media_types CROSS JOIN tracks WHERE Trackid <= 3;")
dbGetQuery(chinookdb, "SELECT * FROM invoices LEFT OUTER JOIN invoice_items ON invoices.InvoiceId = invoice_items.InvoiceId WHERE invoices.InvoiceId <= 3;")
dbGetQuery(chinookdb, "SELECT min(InvoiceID) FROM invoices;")
dbGetQuery(chinookdb, "SELECT max(InvoiceID) FROM invoices;")
dbGetQuery(chinookdb, "SELECT sum(InvoiceID) FROM invoices;")
dbGetQuery(chinookdb, "SELECT avg(InvoiceID) FROM invoices;")
dbGetQuery(chinookdb, "SELECT stdev(InvoiceID) FROM invoices;")
dbGetQuery(chinookdb, "SELECT count(InvoiceID) FROM invoices;")
qrymediatracksdf <- as.data.frame(dbGetQuery(chinookdb, "SELECT * FROM media_types CROSS JOIN tracks WHERE Trackid <= 3;"))
head(qrymediatracksdf)
